project:
  type: website

website:
  title: "KHstats"
  favicon: img/climbing_comic.jpg
  image: img/climbing_comic.jpg
  description: "Thoughts and doodles on (bio)statistics, causal inference, data visualization, R programming, etc."
  twitter-card: 
    image: img/climbing_comic.jpg
    description: "Thoughts and doodles on (bio)statistics, causal inference, data visualization, R programming, etc."
    card-style: summary
  open-graph: true
  page-navigation: true
  google-analytics: "UA-136820093-1"
  site-url: "www.khstats.com"
  search: 
    location: navbar
    type: overlay
  navbar:
    left:
      # - about.qmd
      - blog.qmd
      - talks.qmd
      - sidebar:art
      - sidebar:research
    right:
      - icon: twitter
        href: https://twitter.com/kat_hoffman_
      - icon: bluesky
        href: https://bsky.app/profile/kathoffman.bsky.social
      - icon: github
        href: https://github.com/kathoffman
      - text: CV
        file: /static/KatherineHoffman_CV_Sept2023.pdf
      - icon: envelope
        href: mailto:kathoffman.stats@gmail.com


  sidebar:
    - id: research
      collapse-level: 1
      foreground: dark
      title: "Research"
      style: "docked"
      background: light
      contents:
        - text: "Statistics Methods"
          file: pubs/pubs_methods.qmd
        - text: "Clinical Applications"
          file: pubs/pubs_applications.qmd
        - text: "Google Scholar Profile"
          href: https://scholar.google.com/citations?user=73RvTUoAAAAJ&hl=en
    - id: art
      collapse-level: 1
      title: "Illustrations"
      style: "docked"
      contents:
        - text: "Visual Guides for Causal Inference"
          file: art/illustrations_viz.qmd
        - text: "Educational Drawings and Comics"
          file: art/illustrations_draw.qmd

format:
  html:
    smooth-scroll: true
    theme: [minty, styles.css]
    highlight-style: github
    link-external-icon: false
    link-external-newwindow: true
    citations-hover: true
    footnotes-hover: true
    anchor-sections: true
    code-link: false
    code-block-bg: "#f1f3f5"
    code-block-border-left: "#31BAE9"
    reference-location: margin
    fig-cap-location: margin
    grid:
      body-width: 850px
      margin-width: 300px

editor: source

